{{- $root := . -}}
{{- range $svcName, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" $root }}-{{ $svcName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $svcName | quote }}
    {{- with $svc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/component: {{ $svcName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app.kubernetes.io/component: {{ $svcName }}
        {{- with $svc.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $svc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $root.Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $svc.serviceAccountName }}
      serviceAccountName: {{ $svc.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ $svcName }}
          image: "{{ $svc.image }}:{{ $svc.tag | default "latest" }}"
          imagePullPolicy: {{ $svc.pullPolicy | default "IfNotPresent" }}
          {{- with $svc.command }}
          command: {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with $svc.args }}
          args: {{ toYaml . | nindent 10 }}
          {{- end }}
          env:
            {{- range $k, $v := $svc.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if $svc.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ $svc.envFromSecret }}
          {{- end }}
          {{- if $svc.ports }}
          ports:
            {{- range $p := $svc.ports }}
            - name: {{ $p.name }}
              containerPort: {{ $p.containerPort }}
              protocol: {{ $p.protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          {{- with $svc.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $svc.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $svc.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if $svc.volumeMounts }}
          volumeMounts:
            {{- toYaml $svc.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if $svc.volumes }}
      volumes:
        {{- toYaml $svc.volumes | nindent 8 }}
      {{- end }}
      {{- with $svc.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $svc.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $svc.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}

---